<?php
/** Regression checks for the reproduced audit gaps, using disposable data only. */
if(PHP_SAPI!=='cli'||!isset($pdo,$ids,$port,$checks)){http_response_code(404);exit;}
$role=$pdo->query("SELECT role_id FROM roles WHERE role_name='Donor'")->fetchColumn();
$pdo->prepare('INSERT INTO users(role_id,email,password_hash,first_name,last_name,public_reference) VALUES(?,?,?,?,?,?)')->execute([$role,'audit@example.test',password_hash('Safe-Demo!2026',PASSWORD_DEFAULT),'Audit','Donor',publicReference('USR')]);
$auditDonor=(int)$pdo->lastInsertId();login('audit','audit@example.test');$auditCsrf=token('audit');
request('audit','backend/eligibility_handler.php','POST',$answers+['csrf'=>$auditCsrf]);
$auditCampaign=request('admin','api/index.php/campaigns','POST',array_replace($campaignData,['title'=>'Audit future campaign','total_slots'=>20]),true,$admin)['json']['data']['campaign_id'];
$oldCampaign=request('admin','api/index.php/campaigns','POST',array_replace($campaignData,['title'=>'Audit historical campaign']),true,$admin)['json']['data']['campaign_id'];
$pdo->prepare('UPDATE campaigns SET campaign_date=? WHERE campaign_id=?')->execute([$past,$oldCampaign]);
$pdo->prepare("INSERT INTO appointments(donor_id,campaign_id,scheduled_time_slot,appointment_status,qr_pass_token,public_reference) VALUES(?,?,'08:30:00','Pending',?,?)")->execute([$auditDonor,$oldCampaign,bin2hex(random_bytes(16)),publicReference('REG')]);
$oldAppointment=(int)$pdo->lastInsertId();
$attempt=request('audit','api/index.php/appointments','POST',array_replace($booking,['campaign_id'=>$auditCampaign,'email'=>'audit@example.test']),true,$auditCsrf);
check($attempt['code']===201,'Past unresolved pending booking does not permanently block a new booking');
request('staff','api/index.php/appointments/'.$oldAppointment,'DELETE',['cancellation_reason'=>'Audit fixture cleanup'],true,$staff);
request('audit','api/index.php/appointments','POST',array_replace($booking,['campaign_id'=>$auditCampaign,'email'=>'audit@example.test']),true,$auditCsrf);
$auditAppointment=(int)$pdo->query('SELECT MAX(appointment_id) FROM appointments WHERE donor_id='.$auditDonor)->fetchColumn();
$before=(int)$pdo->query('SELECT COUNT(*) FROM notifications WHERE user_id='.$auditDonor)->fetchColumn();
$confirmation=request('staff','api/index.php/appointments/'.$auditAppointment,'PUT',['appointment_status'=>'Confirmed'],true,$staff);
$after=(int)$pdo->query('SELECT COUNT(*) FROM notifications WHERE user_id='.$auditDonor)->fetchColumn();
check($confirmation['code']===200&&$after===$before+1,'Confirming an appointment creates a persistent donor notification.');
request('audit','backend/eligibility_handler.php','POST',array_replace($answers,['medication'=>'yes','csrf'=>$auditCsrf]));
$auditCheck=latestEligibility($pdo,$auditDonor);
request('staff','api/index.php/screenings/'.$auditCheck['eligibility_id'],'PUT',['outcome'=>'Eligible','review_notes'=>'Audit reviewed decision'],true,$staff);
$reviewPage=request('audit','dashboard.php?view=eligibility&tab=checker')['body'];
check(str_contains($reviewPage,'Medication requires staff review.')&&str_contains($reviewPage,'Audit reviewed decision')&&str_contains($reviewPage,'Original assessment (before staff review)'),'Approved screening separates original assessment from current staff decision.');
request('staff','api/index.php/screenings/'.$auditCheck['eligibility_id'],'PUT',['outcome'=>'Temporarily Deferred','review_notes'=>'Audit active dated deferral','deferred_until'=>$future],true,$staff);
$pdo->prepare('UPDATE campaigns SET campaign_date=? WHERE campaign_id=?')->execute([date('Y-m-d'),$auditCampaign]);
request('staff','api/index.php/appointments/'.$auditAppointment,'PUT',['appointment_status'=>'Checked-In'],true,$staff);
$completed=request('staff','api/index.php/donations','POST',array_replace($donation,['appointment_id'=>$auditAppointment]),true,$staff);
check($completed['code']===409,'Completed intake cannot bypass an active dated deferral.');
$waitingPage=request('audit','dashboard.php?view=eligibility')['body'];
check(str_contains($waitingPage,'Your next eligible donation date is '.$future)&&str_contains($waitingPage,'fresh screening on '.$future),'Waiting summary and screening share the effective return date.');
$cycle=donationProgressState([],[['clinical_outcome'=>'Completed']],false,null,$future);
check($cycle['steps']===[true,true,true,true,true,true],'Waiting period displays the complete previous journey.');
$noSlots=['campaign_date'=>date('Y-m-d'),'start_time'=>'08:00:00','end_time'=>'16:00:00','campaign_status'=>'Published','available_slots'=>2];
$clock=date('Y-m-d').' 15:45:00';
check(campaignRegistrationStatus($noSlots,$clock)==='CLOSED'&&campaignSlots($noSlots,$clock)===[],'Campaign closes after its final generated appointment time.');
$missingBlood=request('staff','api/index.php/donations','POST',['appointment_id'=>$auditAppointment,'clinical_outcome'=>'Deferred','deferral_reason'=>'No collection','deferred_until'=>$future],true,$staff);
check($missingBlood['code']===201,'Deferred outcome succeeds without inventing a collected blood type.');
$ledger=request('staff','api/index.php/transactions?limit=50')['json']['data'];
$originMissing=false;$originFound=false;
foreach($ledger as $item)if($item['transaction_type']==='Adjustment'&&str_contains($item['transaction_notes'],'Required tests complete.')&&empty($item['donor_reference'])&&empty($item['campaign']))$originMissing=true;
foreach($ledger as $item)if($item['transaction_type']==='Adjustment'&&str_contains($item['transaction_notes'],'Required tests complete.')&&!empty($item['donor_reference'])&&!empty($item['campaign']))$originFound=true;
check($originFound&&!$originMissing,'Inventory status-change transactions retain donor and campaign provenance');
check($pdo->query('SELECT blood_type_collected FROM donation_records WHERE appointment_id='.$auditAppointment)->fetchColumn()===null,'Deferred record retains unknown collected blood type as NULL');
check(request('staff','api/index.php/appointments/'.$auditAppointment,'PUT',['appointment_status'=>'Confirmed'],true,$staff)['code']===409,'Terminal outcome cannot return to confirmation');
$sql=campaignStatusSql();$pdo->prepare('UPDATE campaigns SET campaign_date=?,start_time=?,end_time=?,registration_closes_at=NULL WHERE campaign_id=?')->execute([date('Y-m-d'),'08:00:00','16:00:00',$auditCampaign]);
$stmt=$pdo->prepare('SELECT '.$sql.' FROM campaigns c WHERE c.campaign_id=?');$stmt->execute([$clock,$clock,$auditCampaign]);
check($stmt->fetchColumn()==='CLOSED','SQL campaign filter matches the last-slot PHP boundary');
check(request('staff','api/index.php/messages/'.$mid,'PUT',['message_status'=>'Replied','reply_body'=>'Thank you.'],true,$staff)['code']===200 && (int)$pdo->query('SELECT COUNT(*) FROM contact_replies WHERE message_id='.$mid)->fetchColumn()===1,'Retrying a saved reply creates no duplicate delivery attempt');
check(request('audit','api/index.php/notifications/'.(int)$pdo->query('SELECT MIN(notification_id) FROM notifications WHERE user_id='.$ids['Donor'])->fetchColumn(),'PUT',[],true,$auditCsrf)['code']===404,'Notification API rejects another donor record');
